//	VERSION 0.8
#include "type.h"

#if defined(__has_include)
	#if __has_include("Sched.h")
		#include "Sched.h"
		#define ERRORTRAP_RTK_AVAILABLE 1
	#else
		#define ERRORTRAP_RTK_AVAILABLE 0
	#endif
#else
	#define ERRORTRAP_RTK_AVAILABLE 0
#endif

/*    NOTE TO DEBUG HARDFAULT

	1) We found in the ARM Cortex M4 Auxiliary Control Register the DISDEFWBUF bit that when set, 
  disables write buffer use during default memory map accesses. This causes all BusFaults to be 
  precise BusFaults but decreases performance because any store to memory must complete before  
  the processor can execute the next instruction.
  
*/

typedef union{
	DWORD	AsDW;
	struct{
		DWORD IACCVIOL:		1;
		DWORD DACCVIOL:		1;
		DWORD SPARE:		1;
		DWORD MUNSTKERR:	1;
		DWORD MSTKERR:		1;
		DWORD MLSPERR:		1;
		DWORD SPARE1:		1;
		DWORD MMARVALID:	1;
		DWORD IBUSERR:		1;
		DWORD PRECISERR:	1;
		DWORD IMPRECISERR:	1;
		DWORD UNSTKERR:		1;
		DWORD STKERR:		1;
		DWORD LSPERR:		1;
		DWORD SPARE2:		1;
		DWORD BFARVALID:	1;
		DWORD UNDEFINSTR:	1;
		DWORD INVSTATE:		1;
		DWORD INVPC:		1;
		DWORD NOCP:			1;
		DWORD Reserved:		4;		// 20-23
		DWORD UNALIGNED:	1;
		DWORD DIVBYZERO:	1;
		DWORD Reserved1:	6;		// 26-31				
	};
}T_CFSR;

typedef union{
	DWORD	AsDW;
	struct{
		DWORD RESERVED:	1;
		DWORD VECTTBL:	1;	// Indicates a BusFault on a vector table read during exception processing:
		DWORD SPARE:	28;	// When set, the PC value stacked for the exception return points to the instruction that was preempted by the exception.
		DWORD FORCED:	1;  // Indicates a forced hard fault, generated by escalation of a fault with configurable
							// priority that cannot be handles, either because of priority or because it is disabled
		DWORD DEBUGEVT:	1;
	};
}T_HFSR;

typedef union{
	DWORD	AsDW;
	struct{
		DWORD FS:		4;	// Part of the Fault Status field
		DWORD DOMAIN:	4;	// Specifies which of the 16 domains, D15-D0, was being accessed when a data fault occurred.
		DWORD RES:		2;	
		DWORD FS4:		1;  // Part of the Fault Status field
		DWORD WnR:		1;  // 1 if Abort caused by a write access, 0 if read.
		DWORD ExT:		1;  // External abort type.
		DWORD CM:		1;  // Cache maintenance fault. 
	};
}T_DFSR;

volatile T_CFSR _CFSR;
volatile T_HFSR _HFSR;
volatile T_DFSR _DFSR;
volatile unsigned long _AFSR;		// Latched version of AuxFault input;
volatile unsigned long _MMFAR;		// Mem manage fault address register (only if MMARVALID=1)
volatile unsigned long _BFAR;		// BUS Fault address register (only if BFARVALID=1);
volatile unsigned long stacked_r0;
volatile unsigned long stacked_r1;
volatile unsigned long stacked_r2;
volatile unsigned long stacked_r3;
volatile unsigned long stacked_r12;
volatile unsigned long stacked_lr;
volatile unsigned long stacked_pc;
volatile unsigned long stacked_psr;

typedef struct{
	DWORD Magic;						// Marks the snapshot as valid for a post-mortem script.
	DWORD Version;						// Lets the script select the correct snapshot layout.
	DWORD StackedContextPtr;			// Points to the saved core registers at the fault.
	DWORD SelectedSP;					// Shows which stack held the faulted hardware frame.
	DWORD PSP;							// Helps identify the task stack active before the fault.
	DWORD MSP;							// Helps inspect handler or startup stack state at the fault.
	DWORD ExcReturn;					// Tells whether return would use MSP/PSP and basic/FPU frame.
	DWORD CONTROL;						// Shows Thread-mode privilege, stack choice and active FPU context.
	DWORD IPSR;							// Identifies the exception running while the snapshot is taken.
	DWORD PRIMASK;						// Shows whether all maskable interrupts were globally disabled.
	DWORD BASEPRI;						// Shows which interrupt priorities were masked by RTK or application code.
	DWORD FAULTMASK;					// Shows whether every fault except NMI was masked.
	DWORD ICSR;							// Shows pending and active exception state around the fault.
	DWORD SHCSR;						// Shows which system fault handlers were enabled, pending or active.
	DWORD FaultContextException;		// Identifies the interrupted exception; zero means Thread mode.
	DWORD FaultContextIsISR;			// Tells the script that the fault happened inside an ISR or exception.
	DWORD FaultContextIsTask;			// Tells the script that the fault likely happened inside the current RTK task.
	DWORD CurrentTaskPtr;				// Identifies the RTK task descriptor active at the fault.
	DWORD CurrentTaskPSP;				// Gives the task saved stack frame location for deeper inspection.
	DWORD CurrentTaskSavedPC;			// Gives the last scheduler-saved task execution address.
	DWORD CurrentTaskSavedLR;			// Gives the last scheduler-saved task return address.
	DWORD CurrentTaskPriority;			// Helps explain scheduler class and urgency of the current task.
	DWORD CurrentTaskStatus;			// Helps explain whether the current task was ready or waiting.
	DWORD CurrentTaskLabelLow;			// Gives the low 32 bits of the packed human task name.
	DWORD CurrentTaskLabelHigh;			// Gives the high 32 bits of the packed human task name, when available.
	DWORD CurrentTaskWaitObject;		// Identifies the object the task was waiting on, when relevant.
	DWORD CurrentTaskWaitParam;			// Records the mask/value associated with the current wait.
	DWORD CurrentTaskWaitCallerAddress;	// Identifies who put the task in wait, when tracing is enabled.
}T_ErrorTrapSnapshot;

volatile T_ErrorTrapSnapshot ErrorTrapSnapshot;

static DWORD ErrorTrap_ReadCONTROL(void){
	DWORD Value;
	__asm volatile("MRS %0, CONTROL" : "=r"(Value));
	return Value;
}

static DWORD ErrorTrap_ReadIPSR(void){
	DWORD Value;
	__asm volatile("MRS %0, IPSR" : "=r"(Value));
	return Value;
}

static DWORD ErrorTrap_ReadPRIMASK(void){
	DWORD Value;
	__asm volatile("MRS %0, PRIMASK" : "=r"(Value));
	return Value;
}

static DWORD ErrorTrap_ReadBASEPRI(void){
	DWORD Value;
	__asm volatile("MRS %0, BASEPRI" : "=r"(Value));
	return Value;
}

static DWORD ErrorTrap_ReadFAULTMASK(void){
	DWORD Value;
	__asm volatile("MRS %0, FAULTMASK" : "=r"(Value));
	return Value;
}

void HardFault_GetContext(unsigned long* stackedContextPtr, unsigned long excReturn, unsigned long psp, unsigned long msp){
	 
	stacked_r0=stackedContextPtr[0];
	stacked_r1=stackedContextPtr[1];
	stacked_r2=stackedContextPtr[2];
	stacked_r3=stackedContextPtr[3];
	stacked_r12=stackedContextPtr[4];
	stacked_lr=stackedContextPtr[5];
	stacked_pc=stackedContextPtr[6];
	stacked_psr=stackedContextPtr[7];

	_CFSR.AsDW=(*((volatile unsigned long *)(0xE000ED28)));
	_HFSR.AsDW=(*((volatile unsigned long *)(0xE000ED2C)));
	_DFSR.AsDW=(*((volatile unsigned long *)(0xE000ED30)));
	// Read the Fault Address Registers. These may not contain valid values.
	// Check BFARVALID/MMARVALID to see if they are valid values
	// MemManage Fault Address Register
	_MMFAR=(*((volatile unsigned long *)(0xE000ED34)));
	_BFAR=(*((volatile unsigned long *)(0xE000ED38)));
	_AFSR=(*((volatile unsigned long *)(0xE000ED3C)));

	ErrorTrapSnapshot.Magic=0x45545250;
	ErrorTrapSnapshot.Version=1;
	ErrorTrapSnapshot.StackedContextPtr=(DWORD)stackedContextPtr;
	ErrorTrapSnapshot.SelectedSP=(DWORD)stackedContextPtr;
	ErrorTrapSnapshot.PSP=psp;
	ErrorTrapSnapshot.MSP=msp;
	ErrorTrapSnapshot.ExcReturn=excReturn;
	ErrorTrapSnapshot.CONTROL=ErrorTrap_ReadCONTROL();
	ErrorTrapSnapshot.IPSR=ErrorTrap_ReadIPSR();
	ErrorTrapSnapshot.PRIMASK=ErrorTrap_ReadPRIMASK();
	ErrorTrapSnapshot.BASEPRI=ErrorTrap_ReadBASEPRI();
	ErrorTrapSnapshot.FAULTMASK=ErrorTrap_ReadFAULTMASK();
	ErrorTrapSnapshot.ICSR=(*((volatile unsigned long *)(0xE000ED04)));
	ErrorTrapSnapshot.SHCSR=(*((volatile unsigned long *)(0xE000ED24)));
	ErrorTrapSnapshot.FaultContextException=stacked_psr&0x1FF;
	ErrorTrapSnapshot.FaultContextIsISR=(ErrorTrapSnapshot.FaultContextException!=0);
	ErrorTrapSnapshot.FaultContextIsTask=0;
	ErrorTrapSnapshot.CurrentTaskPtr=0;
	ErrorTrapSnapshot.CurrentTaskPSP=0;
	ErrorTrapSnapshot.CurrentTaskSavedPC=0;
	ErrorTrapSnapshot.CurrentTaskSavedLR=0;
	ErrorTrapSnapshot.CurrentTaskPriority=0;
	ErrorTrapSnapshot.CurrentTaskStatus=0;
	ErrorTrapSnapshot.CurrentTaskLabelLow=0;
	ErrorTrapSnapshot.CurrentTaskLabelHigh=0;
	ErrorTrapSnapshot.CurrentTaskWaitObject=0;
	ErrorTrapSnapshot.CurrentTaskWaitParam=0;
	ErrorTrapSnapshot.CurrentTaskWaitCallerAddress=0;

#if ERRORTRAP_RTK_AVAILABLE
	if(KernelRunning && CurrentTaskPtr!=0){
		volatile T_TaskDescriptor *Task=CurrentTaskPtr;
		ErrorTrapSnapshot.CurrentTaskPtr=(DWORD)Task;
		ErrorTrapSnapshot.FaultContextIsTask=(!ErrorTrapSnapshot.FaultContextIsISR && ((excReturn&0x4)!=0));
		ErrorTrapSnapshot.CurrentTaskPSP=(DWORD)Task->PSP;
		ErrorTrapSnapshot.CurrentTaskSavedPC=(DWORD)Task->PSP->PC;
		ErrorTrapSnapshot.CurrentTaskSavedLR=(DWORD)Task->PSP->LR;
		ErrorTrapSnapshot.CurrentTaskPriority=Task->TaskPriority;
		ErrorTrapSnapshot.CurrentTaskStatus=Task->TaskStatus.AsByte;
		ErrorTrapSnapshot.CurrentTaskWaitObject=(DWORD)Task->ObjectToWait.DW;
		ErrorTrapSnapshot.CurrentTaskWaitParam=Task->Param.DW_Param;
		#if TASK_LABEL != 0
			#if TASK_LABEL == 64
				QWORD Label=Task->Label;
				ErrorTrapSnapshot.CurrentTaskLabelLow=(DWORD)Label;
				ErrorTrapSnapshot.CurrentTaskLabelHigh=(DWORD)(Label>>32);
			#else
				ErrorTrapSnapshot.CurrentTaskLabelLow=(DWORD)Task->Label;
				ErrorTrapSnapshot.CurrentTaskLabelHigh=0;
			#endif
		#endif
		#if CALLER_ADDRESS
			ErrorTrapSnapshot.CurrentTaskWaitCallerAddress=(DWORD)Task->WaitCallerAddress;
		#endif
	}
#endif

     	__asm("BKPT #0\n") ; // Break into the debugger
}
 
